version: '3.3'

services:
  sujet_de_priere:
    image: httpd:latest
    container_name: sujet_de_priere
    volumes:
      - .:/usr/local/apache2/htdocs/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sujet_de_priere.rule=Host(`sujet-de-priere.gouale.com`)"
      - "traefik.http.routers.sujet_de_priere.entrypoints=websecure"
    restart: always
    networks:
      - web

networks:
  web:
    external: true
